# Generated by Django 3.0.7 on 2020-08-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_no',
            field=models.CharField(max_length=10),
        ),
    ]
